/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2.group3.TimeKeeper.Viewer;

import java.time.format.DateTimeFormatter;
import java.util.ResourceBundle;
import java2.group3.TimeKeeper.DataObjects.Employee;
import java2.group3.TimeKeeper.DataObjects.TimeRecord;
import java2.group3.TimeKeeper.Logic.MainMenuLogic;

/**
 *
 * @author Skyler Hiscock
 */
public class MainMenuFrame extends javax.swing.JFrame {
    private MainMenuLogic menuLogic = new MainMenuLogic();
    

    /**
     * Creates new form MainMenuFrame
     * @param bundle
     * @param currentEmployee
     */
    public MainMenuFrame(ResourceBundle bundle, Employee currentEmployee) {
        this(bundle, currentEmployee, null);
    }
    
    /**
     *
     * @param bundle
     * @param currentEmployee
     * @param timeRecord
     */
    public MainMenuFrame(ResourceBundle bundle, Employee currentEmployee, TimeRecord timeRecord) {
        this.bundle = bundle;
        this.currentEmployee = currentEmployee;
        this.timeRecord = timeRecord;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserHeader = new javax.swing.JLabel();
        lblProjectHeader = new javax.swing.JLabel();
        lblCurrentUser = new javax.swing.JLabel();
        lblCurrentProject = new javax.swing.JLabel();
        btnEnterTimeRecord = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblStartOrEndHeader = new javax.swing.JLabel();
        lblStartOrEnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(this.bundle.getString("gui_mainmenu_title")
        );

        lblUserHeader.setText(this.bundle.getString("gui_mainmenu_lblcurrentuser"));

        lblProjectHeader.setText(this.bundle.getString("gui_mainmenu_lblcurrentproject"));

        lblCurrentUser.setText(currentEmployee.getFirstName() + " " + currentEmployee.getLastName());

        if(timeRecord != null){
            String projectName = menuLogic.getProjectName(timeRecord);
            if(projectName != null){
                lblCurrentProject.setText(projectName);
            }
        }else{
            lblCurrentProject.setText(bundle.getString("gui_mainmenu_lblnocurrentproject"));
        }

        btnEnterTimeRecord.setText(this.bundle.getString("gui_mainmenu_btnentertimerecord"));
        btnEnterTimeRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterTimeRecordMouseClicked(evt);
            }
        });

        btnExit.setText(this.bundle.getString("gui_mainmenu_btnexit"));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        if(timeRecord == null || timeRecord.getStartOrStop() == 'S'){
            lblStartOrEndHeader.setText(this.bundle.getString("gui_mainmenu_starttime"));
        } else {
            lblStartOrEndHeader.setText(this.bundle.getString("gui_mainmenu_endtime"));
        }

        if(timeRecord != null){
            lblStartOrEnd.setText(timeRecord.getDateTime().format(formatter).toString());
        }else{
            lblStartOrEnd.setText(this.bundle.getString("gui_mainmenu_lblnocurrentproject"));
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblProjectHeader)
                                .addComponent(lblUserHeader))
                            .addComponent(lblStartOrEndHeader))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStartOrEnd)
                            .addComponent(lblCurrentUser)
                            .addComponent(lblCurrentProject))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnterTimeRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserHeader)
                    .addComponent(lblCurrentUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectHeader)
                    .addComponent(lblCurrentProject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartOrEndHeader)
                    .addComponent(lblStartOrEnd))
                .addGap(18, 18, 18)
                .addComponent(btnEnterTimeRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterTimeRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterTimeRecordMouseClicked
        TimeEntryFrame timeEntry = new TimeEntryFrame(bundle, currentEmployee);
        timeEntry.setLocationRelativeTo(this);
        timeEntry.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEnterTimeRecordMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        LoginFrame loginFrame = new LoginFrame(bundle);
        loginFrame.setLocationRelativeTo(this);
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterTimeRecord;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblCurrentProject;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JLabel lblProjectHeader;
    private javax.swing.JLabel lblStartOrEnd;
    private javax.swing.JLabel lblStartOrEndHeader;
    private javax.swing.JLabel lblUserHeader;
    // End of variables declaration//GEN-END:variables
   
    
    private final ResourceBundle bundle;
    private final Employee currentEmployee;
    private final TimeRecord timeRecord;
    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");



}