/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2.group3.TimeKeeper.Viewer;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Skyler Hiscock
 */
public class MainMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel(Locale locale, String bundleName) {
        this.locale = locale;
        this.bundle = ResourceBundle.getBundle(bundleName, locale);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserHeader = new javax.swing.JLabel();
        lblCurrentUser = new javax.swing.JLabel();
        lblCurrentProject = new javax.swing.JLabel();
        lblProjectHeader = new javax.swing.JLabel();
        btnEnterTimeRecord = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        lblUserHeader.setText(this.bundle.getString("gui_mainmenu_lblcurrentuser"));

        lblCurrentUser.setText("jLabel1");

        lblCurrentProject.setText("jLabel2");

        lblProjectHeader.setText(this.bundle.getString("gui_mainmenu_lblcurrentproject"));

        btnEnterTimeRecord.setText(this.bundle.getString("gui_mainmenu_btnentertimerecord"));

        btnExit.setText(this.bundle.getString("gui_mainmenu_btnexit"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnterTimeRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProjectHeader)
                            .addComponent(lblUserHeader))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurrentUser)
                            .addComponent(lblCurrentProject))
                        .addGap(0, 144, Short.MAX_VALUE))
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserHeader)
                    .addComponent(lblCurrentUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectHeader)
                    .addComponent(lblCurrentProject))
                .addGap(18, 18, 18)
                .addComponent(btnEnterTimeRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterTimeRecord;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblCurrentProject;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JLabel lblProjectHeader;
    private javax.swing.JLabel lblUserHeader;
    // End of variables declaration//GEN-END:variables
    private final ResourceBundle bundle;
    private final Locale locale;

}
