/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2.group3.TimeKeeper.Viewer;

import java2.group3.TimeKeeper.Viewer.LoginPanel;
import java2.group3.TimeKeeper.Viewer.MainMenuPanel;
import java2.group3.TimeKeeper.Viewer.TimeEntryPanel;
import java2.group3.TimeKeeper.Viewer.TimeKeeper;

import java.awt.CardLayout;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JPanel;

/**
 *
 * @author Skyler Hiscock
 */
public class TimeKeeper extends javax.swing.JFrame {

    /**
     * Creates new form TimeKeeper
     */
    public TimeKeeper(Locale locale, String bundleName) {
        loginPanel = new LoginPanel(locale, bundleName);
        mainMenuPanel = new MainMenuPanel(locale, bundleName);
        timeEntryPanel = new TimeEntryPanel(locale, bundleName);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCurrentPanel(String panelName) {
        JPanel newPanel = null;
        switch (panelName) {
            case "loginPanel":
                newPanel = loginPanel;
                break;
            case "mainMenuPanel":
                newPanel = mainMenuPanel;
                break;
            case "timeEntryPanel":
                newPanel = timeEntryPanel;
                break;
            default:
                break;
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().removeAll();
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(newPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private LoginPanel loginPanel;
    private MainMenuPanel mainMenuPanel;
    private TimeEntryPanel timeEntryPanel;

}
