/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2.group3.TimeKeeper.Viewer;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Skyler Hiscock
 */
public class TimeEntryPanel extends javax.swing.JPanel {

    /**
     * Creates new form TimeEntryPanel
     */
    public TimeEntryPanel(Locale locale, String bundleName) {
        this.locale = locale;
        this.bundle = ResourceBundle.getBundle(bundleName, locale);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        lblselectproject = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rdoStarting = new javax.swing.JRadioButton();
        rdoEnding = new javax.swing.JRadioButton();
        btnStoreRecord = new javax.swing.JButton();

        buttonGroup.add(rdoStarting);
        buttonGroup.add(rdoEnding);

        lblselectproject.setText(this.bundle.getString("gui_timeentry_lblselectproject"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                this.bundle.getString("gui_timeentry_tbltitleprojectname"), this.bundle.getString("gui_timeentry_tbltitleprojectdesc")
            }
        ){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(125);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(525);
        model = (DefaultTableModel) jTable1.getModel();
        jScrollPane2.setViewportView(jTable1);

        rdoStarting.setText(this.bundle.getString("gui_timeentry_rdostarting"));

        rdoEnding.setText(this.bundle.getString("gui_timeentry_rdoending"));

        btnStoreRecord.setText(this.bundle.getString("gui_timeentry_btnsaverecord"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoEnding)
                            .addComponent(rdoStarting))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStoreRecord))
                    .addComponent(lblselectproject)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblselectproject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rdoStarting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoEnding))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnStoreRecord)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addRowToTable(String projectName, String projectDesc) {
        model.addRow(new Object[]{projectName, projectDesc});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStoreRecord;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblselectproject;
    private javax.swing.JRadioButton rdoEnding;
    private javax.swing.JRadioButton rdoStarting;
    // End of variables declaration//GEN-END:variables

    private final ResourceBundle bundle;
    private final Locale locale;
    private DefaultTableModel model;

}
